### PR TITLE
Always show -> icon

### LINKED ISSUE #99: Missing -> icon
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The `->` (green arrow) icon has been missing for a while now. I assumed it was intentional, but it appears to be a combination of [this check](https://github.com/atom/autocomplete-snippets/blob/ade72c2d4402cdf6292217ca64401164f5cc192f/lib/snippets-provider.js#L9) and the corresponding setting [being removed](https://github.com/atom/autocomplete-plus/commit/7c72e4c1a4d858b4e5251d3623b0426c95d8a4fd) from `autocomplete-plus`.

### Steps to Reproduce

1. Remove `defaultProvider` from your config file if it's there
2. Look at a snippet suggestion

**Expected behavior:** [What you expect to happen]

Green arrow to indicate snippet

**Actual behavior:** [What actually happens]

No icon, like a literal text insertion from `autocomplete-plus`

*Edit by @rsese to drop screenshots*

1.33.0:

1.29.0:

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Atom    : 1.33.0-beta3
autocomplete-plus: 2.42.0
autocomplete-snippets: 1.12.0

### Additional Information

Don't think this was intentional, because it currently makes snippets look like literal text.

### PR DESCRIPTION
**Pull request by Aerijo**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

The `->` green arrow has been missing from snippets provided by this package. This sets `showIcon` to always true, instead of the existing check against the value of an autocomplete-plus setting (which was removed anyhow).

### Alternate Designs

Could have removed the property entirely, but this is more backwards compatible with any packages that rely on setting this property when a snippet provider is created.

### Benefits

Always get the `->` indicator for snippets

### Possible Drawbacks

I'm not actually sure why this was tied to the default autocomplete-plus provider. If someone cares to share, I'm all ears. As far as I can tell though, it would always apply the icons anyway because both default providers were checked for (until the setting was removed altogether).

### Applicable Issues

Fixes #99

### CODE REVIEW

**Comment by Aerijo** [comment]
Well, the tests don't work.

**Comment by rsese** [comment]
This is ready for review @Aerijo?

**Comment by Aerijo** [comment]
I think so. Technically could add a test, but I don’t thinks it’s necessary.

More important are the flaky tests, but that’s not related to this PR.

**Comment by lee-dohm** [comment]
Are there any tests around the original behavior? They should probably be updated if there are.

**Comment by Aerijo** [comment]
@lee-dohm There were no tests for the icons.

I think the flaky tests are a race condition between an event to show suggestions and the synchronous tests.

**Comment by jasonrudolph** [comment]
I tested this out locally, and it seems to be working nicely. Thanks, @Aerijo. :bow:

**Pull request merged**
